### ISSUE TITLE
Stuck on “msgCheckingForUpdate”

### ISSUE THREAD

**Issue by jesus2099** [violentmonkey/violentmonkey-oex#35]
I have [updated a library](https://github.com/jesus2099/konami-command/commit/523a63e818929244223853022746b65b66723d44) called **SUPER.js**.

This new version was then automatically made [available at greasyfork.org](https://greasyfork.org/scripts/10888-super) (auto‐update).
There, its version went from [61168](https://greasyfork.org/scripts/10888-super/code/SUPER.js?version=61168) to [66008](https://greasyfork.org/scripts/10888-super/code/SUPER.js?version=66008&v=2015.8.5.1555).

Then, in a single [later commit](https://github.com/jesus2099/konami-command/commit/94ecc536e9d19221b5d98e79499df3563330cdcb), a script, called **mb_PENDING-EDITS.user.js**, was [added the `@require …SUPER.js?version=66008` line](https://github.com/jesus2099/konami-command/commit/94ecc536e9d19221b5d98e79499df3563330cdcb#diff-dbbce41fb3534748481f098a00bf5a53R20) and another script, called **mb_SUPER-MIND-CONTROL-II-X-TURBO.user.js**, got its already [existing `@require …SUPER.js…` line, updated version](https://github.com/jesus2099/konami-command/commit/94ecc536e9d19221b5d98e79499df3563330cdcb#diff-e87827441bce14262d8816044904e49bL20).

Then I have clicked the **buttonUpdateAll** and all my scripts went OK.
**Except those two scripts** (the only scripts that are using a lib), that are now stuck on **msgCheckingForUpdate** and their individual **buttonUpdate** is still disabled.

**Comment by gera2ld** [comment]
Did you see "msgCheckingForUpdate", "buttonUpdateAll", etc. directly? That is not normal...

**Comment by gera2ld** [comment]
I am really confused about what the problem is about.
Can you simply describe what you did and what you got?
Do you mean that the script was actually updated but got stuck on updating status?

**Comment by jesus2099** [comment]
I saw the French texts, I mentioned the text keys because you may not be familiar with the French version, but it seems it added more confusion, sorry. :)

Yes, the scripts got stuck on updating status. I don't remember if they got updated, I think so, yes.
I told you the detailed steps and told about the library because it's the first time I use library and it is the first time I get this bug as well. I thought it could be related, as the other scripts updated OK as usual.

**Comment by jesus2099** [comment]
I think you might cancel this as “cannot reproduce” as it seems to not happen every time…
Maybe I was just in a strange context that time.

**Comment by gera2ld** [comment]
OK, it might be a network problem, and it's important to know whether the script is really updated while stuck.

**Comment by jesus2099** [comment]
The scripts were updated, but I can't tell if the linked library was updated or not, I didn't know where to look at.

**Comment by jesus2099** [comment]
Let us re-open if it happens again. It has not happened again for quite a long time; it may have been because of bad networkl.
