### ISSUE TITLE
Two requests sent for script installation

### ISSUE THREAD

**Issue by Martii** [violentmonkey/violentmonkey-oex#40]
@gera2ld
So I've been reverifying all the browsers in my arsenal and it appears that Presto with VM is calling on .user.js twice:

``` sh-session
GET /install/Marti/RFC_2606%C2%A73_-_Hello,_World!.user.js 200 136.160 ms - -
GET /install/Marti/RFC_2606%C2%A73_-_Hello,_World!.user.js 429 3.932 ms - -
```
... this is from a click on the Install button on OUJS. e.g. VM on Presto causes our attack prevention to kick in. We don't currently plan on allowing any "free retries" so I was hoping that you could do something about this perhaps in the extension itself. e.g. cache what was requested and then load that into the script editor.

TIA
OUJS Admin

P.S. Not present in Blink based VM.

**Comment by Martii** [comment]
Kewl and thanks. When does this appear [in the store](https://addons.opera.com/en/extensions/details/violent-monkey/?)?

**Comment by Martii** [comment]
Hmmm would appear that [Maxthon version](https://github.com/violentmonkey/violentmonkey-mx) has this same issue too. :\

**Comment by gera2ld** [comment]
The new version is submitted and should be published after one or two workdays.
