### ISSUE TITLE
Few issues with current HEAD

### ISSUE THREAD

**Issue by Martii** [violentmonkey/violentmonkey-oex#41]
[oujs - Meta View](https://openuserjs.org/scripts/Marti/oujs_-_Meta_View) doesn't appear to work in the latest VM-oex.

* `location` is undefined... I could work around that by prefixing with `window.` and [temporarily did](https://github.com/Martii/UserScripts/commit/0dd03becbc83399f7fc857829db8c939aaed2687)... however really shouldn't need to e.g. [reverted](https://github.com/Martii/UserScripts/commit/6b856dfc520747c4d1f79b3f50347ac462d8b186).
* `XMLHttpRequest` is undefined ... that is a DOM global used [here](https://github.com/Martii/UserScripts/blob/de516e7d25a2dd2619882cfcbd4197cb208331b8/src/oujs/Meta%20View/oujs%20-%20Meta%20View.user.js#L228).

These do *(and this script does)* work with VM-oex 1.6.9.2 from [the Opera store](http://addons.opera.com/extensions/details/violent-monkey/?hidemessage=1).

TIA

```
Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
violentmonkey-oex 1.7.0
```

**Comment by gera2ld** [comment]
Sorry for the bug. This is an old and Presto-specific issue which was carried out by refactoring. I will fix it soon.

**Comment by Martii** [comment]
Awesome... thanks so much... btw what is the best way to get this into Presto before it's in the store? I'm using a rather hackish way of testing it out. https://github.com/violentmonkey/violentmonkey-oex#development is a little vague to me. How do I "install the /dist" folder other than run the build, then create my own .oex and drop it in. The `-widget` switch doesn't appear to work here.

**Comment by gera2ld** [comment]
First, open the extension managing page (Ctrl-Shift-E).
Then drag `dist/config.xml` into the page.

Ignore below if it works.
This may fail if `%LocalAppData%\Opera\Opera12\widgets\widgets.dat` is not clean. In that case you may remove the extra or invalid entries manually and retry it.

BTW, the latest `.oex` is available in [releases](https://github.com/violentmonkey/violentmonkey-oex/releases).

**Comment by Martii** [comment]
Thank you again. Had to delete my profile and start over then drag-n-drop worked.

**Comment by jesus2099** [comment]
@Martii I’m here from https://github.com/violentmonkey/violentmonkey-oex/issues/45#issuecomment-219743960
I have dragged `config.xml`, the developer mode appeared but this dev‐mode extension was not functioning (I did disable the live extension).
Could you explain how you did install an arbitrary checked out version of the extension?

**Comment by Martii** [comment]
@jesus2099 
Save the .oex file from releases and then drag-n-drop *(dnd)* it into presto. Should prompt you. Process is different for blink based opera.

**Comment by jesus2099** [comment]
[dev branch](https://github.com/violentmonkey/violentmonkey-oex/commits/dev) (7bbb71745c4fa3772b7c41560895d329fc6187b9 in particular) is ahead of latest versions but, now that you say that, I will download the latest `oex` and change its content with winzip. Thanks. :)
