### ISSUE TITLE
Extension not working anymore

### ISSUE THREAD

**Issue by deathkiller666** [violentmonkey/violentmonkey-oex#45]
Everything was working normally until about 12 hours ago, after which none of the extensions working through Violentmonkey are loading at all. 

I am using Opera 12.18 32bit on Windows 7, and I don't think anything else has updated other than Violentmonkey in the meantime. Tried both VM-oex 1.7.0 and 1.7.0.1 but neither of them worked. 

Javascript console gives a widget error on 4chan where I use this extension https://github.com/loadletter/4chan-x and on every other site it says Linkify plusplus won't load because GM_Config is an undefined variable. 

![untitled](https://cloud.githubusercontent.com/assets/3485711/15096624/7a21ad1e-150a-11e6-99ac-baf93b09b935.png)

**Comment by deathkiller666** [comment]
Did not seem to fix the issue. 

Tried clean installs of both Opera 12.17 and 12.18, both international 32 bit Windows versions. 
Installed Violentmonkey 1.7.1 to both of them, and installed 4chanX as linked in OP. 
Opened 4chan.org, opened a random board and a random thread to see extension not working properly. Picture below to show how it should work and how it suddenly works w/ Opera 12 & VM-oex 1.7.0, 1.7.0.1 and 1.7.1
![untitled](https://cloud.githubusercontent.com/assets/3485711/15159553/df78278e-16fd-11e6-8b88-79c5dc694e9e.png)

Unfortunately I'm not certain what version of VM I was running when everything worked fine until saturday the 7th evening GMT. I don't remember manually updating VM and I'm not sure if Opera updates extensions automatically with delay. Possibly 1.6.9.3 was still working properly, but I can't test it due to no .oex and I don't know how or if possible to compile such from source on Windows.

**Comment by gera2ld** [comment]
The script is executed, but an error occurs:

> Uncaught exception: Error: WRONG_ARGUMENTS_ERR
> Error thrown at line 481, column 6 in <anonymous function: prepend>(parent, children):
>     return parent.insertBefore($.nodes(children), parent.firstChild);
> called from line 2698, column 8 in <anonymous function: initReady>():
>     $.prepend(setting, [$.tn('['), a, $.tn('] ')]);
> called from line 339, column 8 in <anonymous function: cb>():
>     return fc();

It seems that [Node.insertBefore](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore) only supports one node instead of an array of nodes as the first parameter.
When I modify this function, it works.

**Comment by deathkiller666** [comment]
Well, it and other extensions worked before, they work with Greasemonkey on another browser, and they work with Opera's native user js support, albeit a bit worse than through Violentmoneky. Any possibility to get .oex files for some older releases?

**Comment by jesus2099** [comment]
FWIW I have noticed the following following two things that may be related:

Ⅰ
==

I used to use `self` shortcut for `window` functions (example `self.getComputedStyle()` or `self.open`).
It ceased to work recently, I don’t know if it’s because of Opera 12.18 update or Violent monkey update.
I had to change them all to implicit `getComputedStyle()` or explicit `window.getComputedStyle()` — those both work instead of `self` which does not work any more.

Ⅱ
==

Also, recently I too have seen many many many hundreds offollowing error in console:

> Uncaught (in promise) [object Error]

It would be helpful to see the content of that `Error` object, maybe…

Scripts are running fine. I have tons of script so I can’t really tell if they all run fine, actually.

**Comment by jesus2099** [comment]
Wow @gera2ld, it's really impressive! You're dealing with stuff that completely astound me! :bow:
Thanks so much for updating this extension for classic Opera.

**Comment by deathkiller666** [comment]
Everything works again. Thank you.

**Comment by gera2ld** [comment]
@deathkiller666 @jesus2099 sorry for the stupid bug.

**Comment by jesus2099** [comment]
I am so grateful for this extension, @gera2ld! I am happy that you so quickly debugged it. Thanks also to @deathkiller666‘s prompt and complete report. :)

**Comment by jesus2099** [comment]
@gera2ld, how much time does it usually take between a new release (like [1.7.2](/violentmonkey/violentmonkey-oex/commit/8fe444d57ec3039fd5993593fc1c2a14640dcf8b), two days ago) and when it is eventually updated on [official extension](//addons.opera.com/extensions/details/violent-monkey)?

**Comment by gera2ld** [comment]
@jesus2099 Usually one or two workdays, sometimes more, depends on Opera stuff.

**Comment by jesus2099** [comment]
I have installed the 1.7.2 version from [extension page](http://addons.opera.com/extensions/details/violent-monkey/) (which is currently erroring `502 Bad Gateway`, BTW) but my scripts keep saying:

> TypeError: Cannot convert '`self.location`' to object

**Comment by jesus2099** [comment]
Are you planning to make it a `1.7.2.1` soon?
I tried to install the current dev extension by checking out the `dev` branch then drag and dropping `src/config.xml` file into Opera’s **Extensions** panel but it does not really run this way… :confused:

**Comment by jesus2099** [comment]
[dev branch](https://github.com/violentmonkey/violentmonkey-oex/commits/dev) is ahead of latest versions but, now that yo usay that, I will download the latest `oex` and change its content with winzip. :)

**Comment by jesus2099** [comment]
Thanks very much @gera2ld :heart_eyes: [it is now deployed as version 17.2.1 in the extension site](https://addons.opera.com/extensions/details/violent-monkey)!
At first sight, my scripts are running back again. I’ll tell you if I find any other regressions from that refactoring.
